# Generated by Django 5.2.17 on 2026-08-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes_public',
            field=models.BooleanField(default=True),
        ),
    ]
